spring:
  config:
    import:
      - optional:file:config/dev/application-central.yml
      - optional:file:config/prod/application-central.yml

ss220:
  api:
    central:
      # Just an example. Use config/dev/application-central.yml to provide your own values.
      endpoint: http://localhost:8080
      token: example_central_token
