spring:
  config:
    import:
      - optional:file:config/dev/application-bandastation.yml
      - optional:file:config/prod/application-bandastation.yml
  datasource:
    bandastation:
      # Just an example. Use config/dev/application-bandastation.yml to provide your own values.
      url: jdbc:mariadb://localhost:3307/bandastation
      username: root
      password: password

ss220:
  integration:
    game:
      builds:
        bandastation:
          enabled: true
