spring:
  application:
    name: ss220-manager
    revision: snapshot
  config:
    import:
      - optional:file:config/dev/application.yml
      - optional:file:config/prod/application.yml
  datasource:
    bc:
      url: jdbc:h2:./app-database;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
      username:
      password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  main:
    banner-mode: off

jda:
  intents:
    - GUILD_MEMBERS

botcommands:
  core:
    disableExceptionsInDMs: true
  application:
    forceGuildCommands: true
  components:
    enable: true
  app:
    emojis:
      enable: true

ss220:
  discord:
    token: example_bot_token
    profile:
      nickname: SS220 Manager
    game:
      whitelists:
        - name: prime
        - name: devtest
  schedules:
    whitelist-validation:
      cron: "@hourly"

logging:
  discord:
    dispatchChannelId: 0
    dispatchInterval: 360
