spring:
  config:
    import:
      - optional:file:config/dev/application-paradise.yml
      - optional:file:config/prod/application-paradise.yml
  datasource:
    paradise:
      # Just an example. Use config/dev/application-paradise.yml to provide your own values.
      url: jdbc:mariadb://localhost:3306/paradise
      username: root
      password: password

ss220:
  integration:
    game:
      builds:
        paradise:
          enabled: true
