spring:
  config:
    import: optional:classpath:/config/dev/application-redis.yml
  data:
    redis:
      # Just an example. Use config/dev/application-redis.yml to provide your own values.
      host: localhost
      port: 6379
      password: ""

ss220:
  integration:
    redis:
      enabled: true
