spring:
  application:
    name: ss220-manager
    revision: snapshot
  config:
    import:
      - optional:file:config/dev/application.yml
      - optional:file:config/prod/application.yml
  datasource:
    bc:
      url: jdbc:h2:./app-database;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
      username:
      password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  main:
    banner-mode: off

jda:
  intents:
    - GUILD_MEMBERS

botcommands:
  core:
    disableExceptionsInDMs: true
  application:
    forceGuildCommands: true
  components:
    enable: true
  app:
    emojis:
      enable: true

ss220:
  discord:
    token: example_bot_token
    profile:
      nickname: SS220 Manager
    game:
      whitelists:
        - name: prime
        - name: devtest
  schedules:
    whitelist-validation:
      cron: "@hourly"

logging:
  file:
    name: ./log/manager.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      total-size-cap: 1GB
      file-name-pattern: ./log/archive/manager-%d{yyyy-MM-dd}.%i.log
  level:
    root: INFO
    club.ss220: INFO
    org.springframework: INFO
    net.dv8tion.jda: INFO
    com.zaxxer.hikari: INFO
    org.flywaydb: WARN
    io.github.freya022.botcommands: DEBUG
  discord:
    dispatchChannelId: 0
    dispatchInterval: 360
